// client/src/components/Movie.vue
<template>
  <article class="row top-xs c-minfo cover" :style="{ backgroundImage: 'url(' + background + ')' }">
    <div class="col-xs-12">
      <div class="row">
        <h2 class="col-xs-12 c-text">{{movie.title}} ({{movie.year}})</h2>
      </div>
      <div class="row between-xs">
        <span class="col-xs-12 col-sm-6 director">{{movie.director}}</span>
        <span class="col-xs-12 col-sm-6 end-sm">{{movie.production_countries}}</span>
      </div>
    </div>
    <!--<div class="col-xs-12">
      <div class="row between-xs">
        <span class="col-xs-12 col-sm-6 director">{{movie.director}}</span>
        <span class="col-xs-12 col-sm-6 end-sm">{{movie.production_countries}}</span>
      </div>
    </div>-->
    <!--<div class="col-xs-12">
      <div class="row between-xs">
        <span class="col-xs-12 col-sm-6 ">{{movie.actors}}</span>
        <span class="col-xs-12 col-sm-6 end-sm">{{movie.genres}}</span>
      </div>
    </div>
    <div class="col-xs-12 bottom-spacer">
      <div class="row between-xs">
        <div class="col-xs-12 col-sm-9">
          <span class="label">{{movie.resolution}}</span>
          <span class="label secondary spacer">{{movie.location}}</span>
          <span class="label">{{movie.id}}</span>
        </div>
        <div class="col-xs-12 col-sm-3 end-sm">
          {{watched}}
          <span class="label"><i class="icon-plus"></i>&nbsp;{{movie.added}}</span>
        </div>
      </div>
    </div>
    <div class="col-xs-12 bottom-spacer">
      <span>{{movie.overview}}</span>
    </div>-->

  </article>
</template>

<script>
export default {
  name: 'movie',

  props: {
    movie: {
      type: Object,
      required: true,
    },
  },

  computed: {
    watched() {
      return this.movie.count_watched > 0;
    },

    background() {
      return `/img/b${this.movie.backdrop}`;
    },
  },
};
</script>

<style lang="scss" scoped>
@import "../styles/_settings.scss";

.c-minfo {
	font-size: 0.9em;
	margin-bottom: 2em;
	border-bottom: 1px solid $article-border-color;

  height: 765px;
  // background-size: cover;

	.director {
		color: $director-color;
		font-weight: bold;
	}
}

.c-text {
  color: #fff;
  text-shadow: 0 1px 0 hsla(0,0%,0%,.75), 0 0 1px hsla(0,0%,0%,.75), 0 1px 5px hsla(0,0%,0%,.75);
  background: linear-gradient(to bottom, rgba(0,0,0,0.65) 0%,rgba(0,0,0,0) 100%);
}
</style>

// client/js/Movie.jsx
const 	React 			= require('react'),
		DatePicker 		= require('react-datepicker'),
		moment 			= require('moment')

module.exports = React.createClass({
	getInitialState: function() {
		return {
			dateWatched: moment(),
			tmdb_id: this.props.movie.tmdb_id,
			rating: this.props.movie.rating
		}
	},

	render: function() {
		const movie = this.props.movie
		const key = this.props.key
		// const options = this.props.options

		// var that = this;

		const setStateTmdbId = function(data) {
			return
		}

		const setStateWatched = function(date) {
			this.setState({
				dateWatched: date
			})
			return
		}

		const setStateRating = function(data) {
			return
		}

		const fixTmdbId = function() {
			return
		}

		const saveWatched = function() {

		}
		
		var watched;

		if (movie.last_watched != '') {
			watched = (
				<span className="label success spacer"><i className="icon-watched"></i>&nbsp;{moment(movie.last_watched).format('MMM DD, YYYY')}</span>
			)
		}

		return (
			<article>
				<div className="col-xs-12">
					<h2>{movie.title} ({movie.year})</h2>
				</div>
				<div className="col-xs-12">
					<div className="row moviep-images">
						<div className="col-xs-12 col-sm-2">
							<img src={"/img/p" + movie.cover} />
						</div>
						<div className="col-xs-12 col-sm-10">
							<img src={"/img/b" + movie.backdrop} />
						</div>
					</div>
				</div>
				<div className="col-xs-12">
					<div className="row between-xs">
						<span className="col-xs-12 col-sm-6 director">{movie.director}</span>
						<span className="col-xs-12 col-sm-6 end-sm">{movie.production_countries}</span>
					</div>
				</div>
				<div className="col-xs-12">
					<div className="row between-xs">
						<span className="col-xs-12 col-sm-6 ">{movie.actors}</span>
						<span className="col-xs-12 col-sm-6 end-sm">{movie.genres}</span>
					</div>
				</div>
				<div className="col-xs-12 bottom-spacer">
					<div className="row between-xs">
						<div className="col-xs-12 col-sm-9">
							<span className="label">{movie.resolution}</span>
							<span className="label secondary spacer">{movie.location}</span>
						</div>
						<div className="col-xs-12 col-sm-3 end-sm">
							{watched}							
							<span className="label"><i className="icon-plus"></i>&nbsp;{moment(movie.added).format('MMM DD, YYYY H:mm')}</span>
						</div>
					</div>
				</div>
				<div className="col-xs-12">
					<span>{movie.overview}</span>
				</div>
				<div className="col-xs-12 bottom-spacer-large">
					<div className="row between-xs">
						<div className="col-xs-12 col-sm-10 top-xs date-picker">
							<input type="text"></input>
							<button className="btn btn-default">Fix</button>
							<DatePicker
								key="{key}"
								placeholderText="YYYY-MM-DD"
								onChange={setStateWatched}
							/>
						</div>
						<div className="col-xs-12 col-sm-2 end-sm top-xs">
							<span className="label"><i className="icon-watched"></i></span>
						</div>
					</div>
				</div>										
			</article>				
		)	
	}
})
