// client/src/components/Movie.vue
<template>
  <article class="row top-xs c-minfo c-align" :style="{ backgroundImage: 'url(' + background + ')' }">
    <div class="col-xs-12">
        <div class="row">
          <h2 class="col-xs-12 col-sm-10 c-title pt2">{{movie.title}} ({{movie.year}})</h2>
          <h2 class="col-xs-12 col-sm-2 c-title end-xs pt2">{{runtime}} | {{movie.imdb_rating}}</h2>
        </div>
        <div class="row between-xs">
          <span class="col-xs-12 col-sm-6 c-text">{{movie.director}}</span>
          <span class="col-xs-12 col-sm-6 end-sm c-text">{{movie.production_countries}}</span>
        </div>
        <div class="row between-xs">
          <span class="col-xs-12 col-sm-6 c-text">{{movie.actors}}</span>
          <span class="col-xs-12 col-sm-6 end-sm c-text">{{movie.genres}}</span>
        </div>
    </div>

    <div class="col-xs-12">
        <div class="c-moverlay">
          <img :src="cover" class="c-cover" />
          <div v-if="watched" class="c-moverlaycover">
            <span>watched</span>
          </div>
        </div>
    </div>

    <div class="col-xs-12 mb2">
      <div class="row between-xs">
        <div class="col-xs-12 col-sm-9">
          <span class="label">{{movie.resolution}}</span>
          <span class="label secondary spacer">{{movie.location}}</span>
          <span class="label">{{movie.id}}</span>
        </div>
        <div class="col-xs-12 col-sm-3 end-sm">
          <span v-if="watched" class="label success mv0 mh2"><i class="fa fa-binoculars mh1"></i>&nbsp;{{lastWatched}}</span>
          <span class="label"><i class="fa fa-plus mh1"></i>&nbsp;{{added}}</span>
        </div>
      </div>
      <div class="row between-xs ph2 mt2">
        <div class="col-xs-12 c-text c-shaded">
          <span>{{movie.overview}}</span>
        </div>
        </span>
      </div>
					<div class="row between-xs middle-xs mt2">
						<div class="col-xs-12 col-sm-2 addon">
							<input class="addon-field" type="number" min="0" step="1" v-model.number="tmdb" />
							<button class="btn btn-default mr2" @click="fixMovie">Fix</button>
							<div v-if="loading" class="loading middle-xs">
                <div class="loading-bar"></div>
                <div class="loading-bar"></div>
                <div class="loading-bar"></div>
                <div class="loading-bar"></div>
							</div>
						</div>
						<div class="col-xs-12 col-sm-4 addon end-xs">
							<div v-if="watched">
                <span class="c-text">History:</span>
                <span class="label success mv0 mh2 ">{{movie.count_watched}}</span>
                <select :value="shows[shows.length-1]" class="c-select">
                  <option v-for="show in shows" :value="show">{{show}}</option>
                </select>
							</div>
						</div>
						<div class="col-xs-12 col-sm-6 addon end-sm">
							<span v-if="hasRating" class="label success mv0 mr2">{{movie.score}}</span>
							<Rating :max="10" :value="movie.score" @rating-selected="setScore" class="mr2" />
              <!--<datepicker v-model="seen" monday-first @selected="setWatched"></datepicker>>-->
              <VueFlatpickr v-model="seen" :options="fpOptions" />
						</div>
					</div>

    </div>
  </article>
</template>

<script>
import format from 'date-fns/format';
// import Datepicker from 'vuejs-datepicker';
import VueFlatpickr from 'vue-flatpickr';
import 'vue-flatpickr/theme/base16_flat.css';

import * as types from '../store/types';
import { hourMinute } from '../lib/utils';
import Rating from './Rating';

const en = {
  weekdays: {
    shorthand: ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'],
    longhand: [
      'Sunday', 'Monday', 'Tuesday', 'Wednesday',
      'Thursday', 'Friday', 'Saturday',
    ],
  },
  months: {
    shorthand: [
      'Jan', 'Feb', 'Mar', 'Apr',
      'May', 'Jun', 'Jul', 'Aug',
      'Sep', 'Oct', 'Nov', 'Dec',
    ],
    longhand: [
      'January', 'February', 'March', 'April',
      'May', 'June', 'July', 'August',
      'September', 'October', 'November', 'December',
    ],
  },
  daysInMonth: [31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31],
  firstDayOfWeek: 1,
  ordinal: (nth) => {
    const s = nth % 100;
    if (s > 3 && s < 21) return 'th';
    switch (s % 10) {
      case 1: return 'st';
      case 2: return 'nd';
      case 3: return 'rd';
      default: return 'th';
    }
  },
  rangeSeparator: ' to ',
  weekAbbreviation: 'Wk',
  scrollTitle: 'Scroll to increment',
  toggleTitle: 'Click to toggle',
};


export default {
  name: 'movie',

  data() {
    return {
      tmdb: this.movie.tmdb_id,
      seen: new Date().toString(),
      fpOptions: {
        onValueUpdate: null,
        onChange: (selectedDates, dateStr, instance) => this.setWatched(selectedDates, dateStr, instance), // eslint-disable-line
        locale: en,
      },
      loading: false,
    };
  },

  props: {
    movie: {
      type: Object,
      required: true,
    },
  },

  components: { Rating, VueFlatpickr },

  methods: {
    setScore(score) {
      this.$store.dispatch(types.SET_SCORE, { id: this.movie.id, score });
    },

    setWatched() {
      // console.log(`seen(${this.seen})`); // eslint-disable-line
      const watched = format(this.seen, 'YYYY-MM-DDTHH:mm:ssZ');
      // console.log(`seen(${lastWatched})`); // eslint-disable-line
      this.$store.dispatch(types.SET_WATCHED, { id: this.movie.id, watched });
    },

    fixMovie() {
      // console.log(`typeof(${typeof this.tmdb})`); // eslint-disable-line
      if (this.tmdb !== this.movie.tmdb_id) {
        this.$store.dispatch(types.FIX_MOVIE, { id: this.movie.id, tmdb: this.tmdb });
      }
    },
  },

  computed: {
    watched() {
      return this.movie.count_watched > 0;
    },

    runtime() {
      return hourMinute(this.movie.runtime);
    },

    added() {
      // const added = parse(this.movie.added);
      return format(this.movie.added, 'MMM DD, YYYY H:mm');
    },

    hasRating() {
      return this.movie.score !== 0;
    },

    lastWatched() {
      return format(this.movie.last_watched, 'MMM DD, YYYY');
    },

    cover() {
      return `img/p${this.movie.cover}`;
    },

    background() {
      return `/img/b${this.movie.backdrop}`;
    },

    shows() {
      return this.movie.all_watched.split('|').map(show => format(show, 'MMM DD, YYYY'));
    },
  },
};
</script>

<style lang="scss" scoped>
@import "../styles/_settings.scss";

.c-minfo {
	font-size: 0.9em;
	margin-bottom: 2em;
	border-bottom: 1px solid $article-border-color;

  height: 765px;
  background-size: cover;

	// .director {
	// 	color: $director-color;
	// 	font-weight: bold;
	// }
}

.c-align {
  align-content: space-between;
}

.c-title {
  color: #fff;
  text-shadow: 0 1px 0 hsla(0,0%,0%,.75), 0 0 1px hsla(0,0%,0%,.75), 0 1px 5px hsla(0,0%,0%,.75);
  background: linear-gradient(to bottom, rgba(0,0,0,0.65) 0%,rgba(0,0,0,0) 100%);
}

.c-text {
  color: #fff;
  text-shadow: 0 1px 0 hsla(0,0%,0%,.75), 0 0 1px hsla(0,0%,0%,.75), 0 1px 5px hsla(0,0%,0%,.75);
}

.c-shaded {
	// font-size: 1.25em;
	color: white;
	background-color: rgba(0, 0, 0, 0.4);
	padding: 0.25em 1em;
}

.c-cover {
  height: 400px;
  width: auto;
  opacity: 0.75;
}

.c-moverlay {
	position: relative;
	overflow: hidden;
}

.c-moverlaycover {
	position: absolute;
	left: -40px;
	top: 10px;
	background-color: rgba(170, 0, 0, 0.6);
	transform: rotate(-45deg);
	box-shadow: 0 0 10px #888;

	span {
		border: 1px solid #faa;
		color: #fff;
		display: block;
		font-size: 0.8em;
		margin: 1px 0;
		padding: 5px 50px;
		text-align: center;
		text-decoration: none;
		/* shadow */
		text-shadow: 0 0 5px #444;
	}
}

.c-select {
  width: 125px;
}
</style>

// ui/src/shared/movie/movie.tsx
import React from "react";

import { format } from "date-fns/format";

import type { Movie } from "~/types";
import { hourMinute } from "~/lib/hour-minute";
import { Icon } from "~/res/icons/icon";
import { Rating } from "~/shared/components/rating";
import { Calendar } from "~/shared/components/calendar";

interface MovieProps {
  index: number;
  item: Movie;
  onFixMovie: ({ index, tmdb_id }: { index: number; tmdb_id: number }) => void;
  onCopyMovie: ({ index, tmdb_id }: { index: number; tmdb_id: number }) => void;
  onRateMovie: ({ index, score }: { index: number; score: number }) => void;
  onWatchedMovie: ({
    index,
    watched,
  }: {
    index: number;
    watched: string;
  }) => void;
}

export const MovieScreen: React.FC<MovieProps> = ({
  index,
  item,
  onFixMovie,
  onCopyMovie,
  onRateMovie,
  onWatchedMovie,
}) => {
  const [value, setValue] = React.useState<number>();
  // const bgImage = `http://localhost:7623/img/b${item.backdrop}`;

  React.useEffect(() => {
    setValue(item.tmdb_id);
  }, [item.tmdb_id]);

  const shows =
    item.all_watched !== ""
      ? item.all_watched
          .split("|")
          .map((show) => format(new Date(show), "MMM dd, yyyy"))
      : [];

  const onValueChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    setValue(+e.target.value);
  };

  const onFix = () => onFixMovie({ index, tmdb_id: value ?? 0 });
  const onCopy = () => onCopyMovie({ index, tmdb_id: value ?? 0 });
  const onRating = (score: number) => onRateMovie({ index, score });
  const onWatched = (watched: string) => onWatchedMovie({ index, watched });

  return (
    <article
      className="bg-cover bg-center bg-no-repeat pb-2 mb-4"
      style={{
        backgroundImage: `url(/img/b${item.backdrop})`,
      }}
    >
      {/* title, year */}
      <div className="flex justify-between bg-gradient-to-b from-black to-black/65 py-1 px-2">
        <span className="[text-shadow:1px_1px_2px_var(--tw-shadow-color)] shadow-black text-slate-50 font-bold text-2xl">
          {item.title} ({item.year})
        </span>
        <span className="[text-shadow:1px_1px_2px_var(--tw-shadow-color)] shadow-black text-slate-50 font-bold text-2xl">
          {`${hourMinute(item.runtime)}`} | {item.imdb_rating}
        </span>
      </div>

      {/* cover */}
      <div className="pl-2 mt-2">
        <div className="relative overflow-hidden">
          <img
            src={`/img/p${item.cover}`}
            className="h-96 opacity-75"
            alt={item.title}
          />
          {item.count_watched > 0 ? (
            <div className="absolute -left-8 top-5 bg-red-900 -rotate-45 shadow-lg shadow-slate-700">
              <span className="[text-shadow:0px_0px_1px_var(--tw-shadow-color)] shadow-white text-white text-sm px-8 py-1 border">
                watched
              </span>
            </div>
          ) : null}
        </div>
      </div>

      <div className="px-2 mt-4">
        <div className="bg-black/25 mt-2 pb-2">
          {/* direct, production_countries */}
          <div className="px-2 flex justify-between">
            <span className="[text-shadow:_0_1px_0_var(--tw-shadow-color),_0_0_1px_var(--tw-shadow-color),_0_1px_5px_var(--tw-shadow-color)] shadow-black/75 text-yellow-400 font-bold">
              {item.director}
            </span>
            <span className="[text-shadow:_0_1px_0_var(--tw-shadow-color),_0_0_1px_var(--tw-shadow-color),_0_1px_5px_var(--tw-shadow-color)] shadow-black/75 text-white font-bold">
              {item.production_countries}
            </span>
          </div>

          {/* actors, genres */}
          <div className="px-2 flex justify-between">
            <span className="[text-shadow:_0_1px_0_var(--tw-shadow-color),_0_0_1px_var(--tw-shadow-color),_0_1px_5px_var(--tw-shadow-color)] shadow-black/75 text-white font-bold">
              {item.actors}
            </span>
            <span className="[text-shadow:_0_1px_0_var(--tw-shadow-color),_0_0_1px_var(--tw-shadow-color),_0_1px_5px_var(--tw-shadow-color)] shadow-black/75 text-white font-bold">
              {item.genres}
            </span>
          </div>

          {/* location */}
          <div className="px-2 mt-4 text-sm">
            <div className="col-span-10">
              <span className="bg-white py-1 px-2 text-sm">
                {item.location}
              </span>
            </div>
          </div>

          {/* id, resolution, added, watched */}
          <div className="flex items-center px-2 mt-4 text-sm">
            <span className=" bg-blue-800 text-slate-50 py-1 px-2">
              {item.id}
            </span>
            <span className=" bg-blue-700 text-slate-50 ml-2 py-1 px-2">
              {item.resolution}
            </span>
            <div className="bg-green-700 text-white ml-2 py-1 px-2 flex items-center">
              <Icon name="plus" size={12} fill="fill-white" />
              <span className="ml-2">
                {format(new Date(item.added), "MMM dd, yyyy")}
              </span>
            </div>
            {item.count_watched > 0 ? (
              <div className="bg-blue-600 text-white ml-2 py-1 px-2 flex items-center">
                <Icon name="binoculars" size={12} fill="fill-white" />
                <span className="ml-2">
                  {format(new Date(item.last_watched), "MMM dd, yyyy")}
                </span>
              </div>
            ) : null}
          </div>

          {/* overview */}
          <div className="px-2 mt-4">
            <span className="[text-shadow:_0_1px_0_var(--tw-shadow-color),_0_0_1px_var(--tw-shadow-color),_0_1px_5px_var(--tw-shadow-color)] shadow-black/75 text-white font-bold">
              {item.overview}
            </span>
          </div>

          {/* tmdb, fix, copy, dup, count_watched, history, score, watched input */}
          <div className="px-2 mt-4 flex justify-between text-sm">
            <div className="flex flex-row">
              <input
                type="number"
                defaultValue={item.tmdb_id}
                value={value}
                onChange={onValueChange}
                className="bg-white text-slate-600 px-2 py-1"
              />
              <button
                className="bg-blue-700 text-white px-4 py-1 ml-2"
                onClick={onFix}
              >
                fix
              </button>
              <button
                className="bg-blue-700 text-white px-2 py-1 ml-2"
                onClick={onCopy}
              >
                copy
              </button>
              <span className="ml-2 flex items-center">
                <span className="text-white">!dup? </span>
                <input type="checkbox" id="dup" className="ml-1" />
              </span>
            </div>

            {item.count_watched > 0 ? (
              <div className="flex items-center">
                <span className="font-bold me-2 px-2.5 py-1 rounded-full bg-green-900 text-green-300">
                  {item.count_watched}
                </span>
                <select
                  className="mr-2 text-slate-600 py-1 px-2 outline-0"
                  value={`${shows[shows.length - 1]}`}
                >
                  {shows.map((show, index) => (
                    <option key={index}>{show}</option>
                  ))}
                </select>
              </div>
            ) : null}

            <div className="flex items-center">
              {item.score > 0 ? (
                <span className="font-bold me-2 px-2.5 py-0.5 rounded bg-red-900 text-red-300">
                  {item.score}
                </span>
              ) : null}
              <Rating rating={item.score} setRating={onRating} />
              <Calendar onChange={onWatched} />
            </div>
          </div>
        </div>
      </div>
    </article>
  );
};
