// client/src/components/Cover.vue
<template>
  <div class="c-mcover">
    <div class="row">
      <div class="col-xs-12">
        <div class="c-moverlay">
          <img :src="'/img/p' + movie.cover" />
          <div v-if="watched" class="c-moverlaycover">
            <span>watched</span>
          </div>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-xs-12">
        <div class="pv0 ph2">
          <p class="c-mctitle">{{movie.title}}</p>
          <div class="between-xs c-mcdetails">
            <span>{{movie.year}}</span>
            <span>{{movie.imdb_rating}}</span>
            <span>{{runtime}}</span>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
import { hourMinute } from '../lib/utils';

export default {
  name: 'cover',

  props: {
    movie: {
      type: Object,
      required: true,
    },
  },

  computed: {
    runtime() {
      return hourMinute(this.movie.runtime);
    },

    watched() {
      return this.movie.count_watched > 0;
    },
  },
};
</script>

<style lang="scss" scoped>
@import "../styles/_settings.scss";

.c-mcover {
  background-color: $movie-cover-bg;
}

.c-moverlay {
	position: relative;
	overflow: hidden;
}

.c-moverlaycover {
	position: absolute;
	left: -40px;
	top: 10px;
	background-color: rgba(170, 0, 0, 0.6);
	transform: rotate(-45deg);
	box-shadow: 0 0 10px #888;

	span {
		border: 1px solid #faa;
		color: #fff;
		display: block;
		font-size: 0.8em;
		margin: 1px 0;
		padding: 5px 50px;
		text-align: center;
		text-decoration: none;
		/* shadow */
		text-shadow: 0 0 5px #444;
	}
}


.c-mctitle {
	color: $movie-title-color;
	white-space: nowrap;
	width: 100%;
	overflow: hidden;              /* "overflow" value must be different from "visible" */
	text-overflow: ellipsis;
}

.c-mcdetails {
	display: flex;
	font-size: 0.75em;
}
</style>

// ui/src/screens/covers/cover.tsx
import React from "react";

import type { Movie } from "~/types";
import { hourMinute } from "~/lib/hour-minute";

interface Props {
  movie: Movie;
}

export const CoverScreen: React.FC<Props> = ({ movie }) => {
  return (
    <div className="bg-neutral-100 text-sm">
      <div className="relative overflow-hidden">
        <img src={`/img/p/${movie.cover}`} />
        {movie.count_watched > 0 ? (
          <div className="absolute -left-8 top-5 bg-red-900 -rotate-45 shadow-lg shadow-slate-700">
            <span className="[text-shadow:0px_0px_1px_var(--tw-shadow-color)] shadow-white text-white text-sm px-8 py-1 border">
              watched
            </span>
          </div>
        ) : null}
      </div>
      <div className="p-2">
        <p className="truncate text-sky-700">{movie.title}</p>
        <div className="flex justify-between text-gray-500">
          <span>{movie.year}</span>
          <span>{movie.imdb_rating}</span>
          <span>{hourMinute(movie.runtime)}</span>
        </div>
      </div>
    </div>
  );
};
